version: "3.8"
services:
  database:
    image: postgres:17
    container_name: zwitter-postgres 
    environment:
      POSTGRES_DB: zwitter
      POSTGRES_PASSWORD: zwitter
      POSTGRES_USER: zwitter
    ports:
      - 5432:5432
    restart: on-failure:3

  redis:
    image: redis:latest
    container_name: zwitter-redis
    command: redis-server
    ports:
      - 6379:6379